// frontend/src/lib/ui/components/ThemeSwitcher.tsx
import { MoonIcon, SunIcon } from '@heroicons/react/24/solid'
import { useEffect, useState } from 'react'

const ThemeSwitcher = () => {
  const [theme, setTheme] = useState<'light' | 'dark'>('light')

  const applyTheme = (value: 'light' | 'dark') => {
    setTheme(value)
    document.documentElement.setAttribute('data-theme', value)
    localStorage.setItem('theme', value)
  }

  const toggleTheme = () => {
    applyTheme(theme === 'light' ? 'dark' : 'light')
  }

  useEffect(() => {
    const saved = localStorage.getItem('theme')
    if (saved === 'light' || saved === 'dark') {
      applyTheme(saved)
      return
    }
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches
    applyTheme(prefersDark ? 'dark' : 'light')
  }, [])

  return (
    <button className="btn btn-square btn-ghost" aria-label="Toggle theme" onClick={toggleTheme}>
      {theme === 'dark' ? <MoonIcon className="h-5 w-5" /> : <SunIcon className="h-5 w-5" />}
    </button>
  )
}

export default ThemeSwitcher

// src/lib/ui/components/ThemeSwitcher.tsx
import { Icon } from 'solid-heroicons'
import { moon, sun } from 'solid-heroicons/solid'
import { createSignal, onMount, Show } from 'solid-js'

const ThemeSwitcher = () => {
  const [theme, setTheme] = createSignal<'light' | 'dark'>('light')

  const applyTheme = (value: 'light' | 'dark') => {
    setTheme(value)
    document.documentElement.setAttribute('data-theme', value)
    localStorage.setItem('theme', value)
  }

  const toggleTheme = () => {
    applyTheme(theme() === 'light' ? 'dark' : 'light')
  }

  onMount(() => {
    const saved = localStorage.getItem('theme')
    if (saved === 'light' || saved === 'dark') {
      applyTheme(saved)
      return
    }
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches
    applyTheme(prefersDark ? 'dark' : 'light')
  })

  return (
    <button class="btn btn-square btn-ghost" aria-label="Toggle theme" onClick={toggleTheme}>
      <Show when={theme() === 'dark'} fallback={<Icon path={sun} class="h-5 w-5" />}>
        <Icon path={moon} class="h-5 w-5" />
      </Show>
    </button>
  )
}

export default ThemeSwitcher
